2021-06-18 00:38:26,624 INFO: My App Startup [in /Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/__init__.py:48
2021-06-18 00:39:52,926 INFO: My App Startup [in /Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/__init__.py:48
2021-06-21 14:57:53,523 INFO: My App Startup [in /Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/__init__.py:48
2021-06-21 14:57:58,335 INFO: My App Startup [in /Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/__init__.py:48
2021-06-21 16:44:31,729 INFO: My App Startup [in /Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/__init__.py:48
2021-06-21 16:45:01,042 INFO: My App Startup [in /Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/__init__.py:48
2021-06-21 20:09:50,480 INFO: My App Startup [in /Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/__init__.py:48
2021-06-21 20:47:42,745 INFO: My App Startup [in /Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/__init__.py:48
2021-06-22 12:15:58,252 INFO: My App Startup [in /Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/__init__.py:48
2021-06-22 12:16:16,330 ERROR: Exception on /index [GET] [in /Users/vincentiuscalvin/anaconda3/envs/personal/lib/python3.8/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/Users/vincentiuscalvin/anaconda3/envs/personal/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vincentiuscalvin/anaconda3/envs/personal/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vincentiuscalvin/anaconda3/envs/personal/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vincentiuscalvin/anaconda3/envs/personal/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vincentiuscalvin/anaconda3/envs/personal/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vincentiuscalvin/anaconda3/envs/personal/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vincentiuscalvin/anaconda3/envs/personal/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/routes.py", line 28, in index
    return render_template('index.html', title='Home', posts=posts, form=form)
  File "/Users/vincentiuscalvin/anaconda3/envs/personal/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/vincentiuscalvin/anaconda3/envs/personal/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/vincentiuscalvin/anaconda3/envs/personal/lib/python3.8/site-packages/jinja2/environment.py", line 1289, in render
    self.environment.handle_exception()
  File "/Users/vincentiuscalvin/anaconda3/envs/personal/lib/python3.8/site-packages/jinja2/environment.py", line 924, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/templates/base.html", line 50, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/templates/index.html", line 22, in block 'content'
    {% include '_post.html' %}
  File "/Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ user.avatar(32) }}" alt=""></td>
  File "/Users/vincentiuscalvin/anaconda3/envs/personal/lib/python3.8/site-packages/jinja2/environment.py", line 473, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2021-06-22 12:17:39,857 INFO: My App Startup [in /Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/__init__.py:48
2021-06-22 12:23:13,425 INFO: My App Startup [in /Users/vincentiuscalvin/Documents/Supertype/Learning Flask/app/__init__.py:48
